In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = [2.7, 7.8, 6.2, 10.7, 9.6, 14.0, 13.2, 16.1, 17.9, 22.2, 23.7, 24.6, 24.6, 28.7, 28.6, 34.5, 34.1, 39.0,
        38.7, 43.2, 42.3, 46.2, 46.3, 48.5, 49.8]

In [6]:
y = np.matrix(data).reshape(len(data), 1)

In [9]:
y.shape

(25, 1)

In [16]:
a_0 = np.matrix(np.ones((len(data), 1)))
a_0

matrix([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [17]:
a_1 = np.matrix(range(1, len(data) + 1)).reshape(len(data), 1)
a_1

matrix([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25]])

In [28]:
b_1 = np.matrix([np.cos(np.pi * i) for i in range(1, len(data) + 1)]).reshape(len(data), 1)
b_1

matrix([[-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.]])

In [30]:
c_1 = np.matrix([np.sin(np.pi * i) for i in range(1, len(data) + 1)]).reshape(len(data), 1)
c_1

matrix([[ 1.22464680e-16],
        [-2.44929360e-16],
        [ 3.67394040e-16],
        [-4.89858720e-16],
        [ 6.12323400e-16],
        [-7.34788079e-16],
        [ 8.57252759e-16],
        [-9.79717439e-16],
        [ 1.10218212e-15],
        [-1.22464680e-15],
        [ 4.89982516e-15],
        [-1.46957616e-15],
        [-1.96067284e-15],
        [-1.71450552e-15],
        [ 5.38968388e-15],
        [-1.95943488e-15],
        [-1.47081412e-15],
        [-2.20436424e-15],
        [ 5.87954260e-15],
        [-2.44929360e-15],
        [-9.80955401e-16],
        [-9.79965032e-15],
        [ 6.36940132e-15],
        [-2.93915232e-15],
        [-4.91096681e-16]])

In [31]:
X = np.hstack([a_0, a_1, b_1, c_1])

matrix([[ 1.00000000e+00,  1.00000000e+00, -1.00000000e+00,
          1.22464680e-16],
        [ 1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         -2.44929360e-16],
        [ 1.00000000e+00,  3.00000000e+00, -1.00000000e+00,
          3.67394040e-16],
        [ 1.00000000e+00,  4.00000000e+00,  1.00000000e+00,
         -4.89858720e-16],
        [ 1.00000000e+00,  5.00000000e+00, -1.00000000e+00,
          6.12323400e-16],
        [ 1.00000000e+00,  6.00000000e+00,  1.00000000e+00,
         -7.34788079e-16],
        [ 1.00000000e+00,  7.00000000e+00, -1.00000000e+00,
          8.57252759e-16],
        [ 1.00000000e+00,  8.00000000e+00,  1.00000000e+00,
         -9.79717439e-16],
        [ 1.00000000e+00,  9.00000000e+00, -1.00000000e+00,
          1.10218212e-15],
        [ 1.00000000e+00,  1.00000000e+01,  1.00000000e+00,
         -1.22464680e-15],
        [ 1.00000000e+00,  1.10000000e+01, -1.00000000e+00,
          4.89982516e-15],
        [ 1.00000000e+00,  1.20000000e+01, 

In [32]:
X.shape

(25, 4)

In [33]:
beta = (X.T * X).I * X.T * y

In [34]:
beta

matrix([[1.12179618e+00],
        [1.98922756e+00],
        [1.08079412e+00],
        [4.77140909e+13]])

In [35]:
y - X* beta

matrix([[ 0.66392709],
        [ 1.63064117],
        [ 0.1737854 ],
        [ 0.56387264],
        [-0.4163563 ],
        [-0.10289589],
        [-0.80649799],
        [-1.96966442],
        [-0.09663969],
        [ 0.16356705],
        [ 1.54370411],
        [-1.40320148],
        [-1.20740857],
        [-1.26997002],
        [-1.53657928],
        [ 0.56326145],
        [ 0.31230804],
        [ 1.09649292],
        [ 0.58313733],
        [ 1.32972439],
        [ 0.53202465],
        [ 0.70198486],
        [ 0.20285394],
        [-1.30381267],
        [ 0.05174126]])